[package]
name = "rmp"
version = "0.8.7"
authors = ["Evgeny Safronov <division494@gmail.com>"]
license = "MIT"
description = "Pure Rust MessagePack serialization implementation"
repository = "https://github.com/3Hren/msgpack-rust"
documentation = "https://docs.rs/rmp"
readme = "README.md"
keywords = ["msgpack", "MessagePack"]
categories = ["encoding"]

[dependencies]
byteorder = { git = "https://github.com/mesalock-linux/byteorder-sgx", rev = "70965e6bda25f6b77f968684e20b902dc2162a9c" }
num-traits = { git = "https://github.com/mesalock-linux/num-traits-sgx", rev = "4fe7ee21ef259c63b79b66b630226957c0e1ae57" }
sgx_tstd = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.8" }


[dev-dependencies]
quickcheck = "0.3"
